import type { KOT } from "@/types";

const now = Date.now();

export const SEED_KOTS: KOT[] = [
  {
    id: "kot-1001",
    tableId: "T-5",
    orderId: "ORD-5001",
    waiterName: "Anita",
    timestamp: now - 4 * 60 * 1000,
    orderSource: "Walk-In",
    items: [
      {
        id: "i-1",
        name: "Butter Chicken",
        quantity: 2,
        price: 380,
        status: "Cooking",
        stationId: "Hot",
        modifiers: ["Extra Spicy", "No Cream"],
        isVoided: false,
      },
      {
        id: "i-2",
        name: "Garlic Naan",
        quantity: 4,
        price: 60,
        status: "Pending",
        stationId: "Hot",
        modifiers: [],
        isVoided: false,
      },
      {
        id: "i-3",
        name: "Mojito",
        quantity: 2,
        price: 220,
        status: "Ready",
        stationId: "Bar",
        modifiers: ["Less Sugar"],
        isVoided: false,
      },
    ],
  },
  {
    id: "kot-1002",
    tableId: "T-5",
    orderId: "ORD-5002",
    waiterName: "Anita",
    timestamp: now - 2 * 60 * 1000,
    orderSource: "Walk-In",
    items: [
      {
        id: "i-4",
        name: "Caesar Salad",
        quantity: 1,
        price: 280,
        status: "Pending",
        stationId: "Cold",
        modifiers: ["No Croutons"],
        isVoided: false,
      },
    ],
  },
  {
    id: "kot-1003",
    tableId: "T-12",
    orderId: "ORD-5003",
    waiterName: "Ravi",
    timestamp: now - 14 * 60 * 1000, // > 12 min → aging alert
    orderSource: "Zomato",
    items: [
      {
        id: "i-5",
        name: "Margherita Pizza",
        quantity: 1,
        price: 420,
        status: "Cooking",
        stationId: "Hot",
        modifiers: ["Thin Crust"],
        isVoided: false,
      },
      {
        id: "i-6",
        name: "Tiramisu",
        quantity: 1,
        price: 250,
        status: "Pending",
        stationId: "Cold",
        modifiers: [],
        isVoided: false,
      },
    ],
  },
  {
    id: "kot-1004",
    tableId: "T-3",
    orderId: "ORD-5004",
    waiterName: "Priya",
    timestamp: now - 7 * 60 * 1000,
    orderSource: "Swiggy",
    items: [
      {
        id: "i-7",
        name: "Paneer Tikka",
        quantity: 1,
        price: 320,
        status: "Ready",
        stationId: "Hot",
        modifiers: [],
        isVoided: false,
      },
      {
        id: "i-8",
        name: "Coke",
        quantity: 2,
        price: 80,
        status: "Ready",
        stationId: "Bar",
        modifiers: [],
        isVoided: false,
      },
    ],
  },
];
